In [1]:
import pandas as pd
import numpy as np
import joblib

In [2]:
from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)


from sklearn.linear_model import LinearRegression
from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor
)

In [3]:
df = pd.read_csv("../data/telecom_dataset.csv")

df.head()

,tower_lat,tower_lon,user_lat,user_lon,distance_km,frequency,tx_power,tower_height,antenna_gain,environment,building_density,terrain_height,shadow_fading,rain_loss,user_density,traffic_load,path_loss,received_power,rsrp
0,8.772803,79.601511,8.348193,81.220791,184.202906,700,40,50,20,Rural,0.044,412.71,3.55,1.189,954.31,0.809,134.647890,-79.386890,-82.386890
1,8.477245,81.539348,6.724820,81.560330,194.874487,3500,43,30,15,Suburban,0.547,55.40,5.07,0.684,28.56,0.204,149.116461,-96.870461,-99.870461
2,8.547476,80.296990,8.629913,80.816295,57.827614,2100,46,50,20,Urban,0.885,70.63,9.12,0.000,1227.02,0.875,134.127091,-77.247091,-80.247091
3,8.607987,79.509811,8.134189,79.992761,74.821865,3500,46,20,15,Rural,0.258,159.33,3.49,1.291,933.28,0.632,140.801931,-84.582931,-87.582931
4,8.630686,81.193634,8.028912,80.930730,72.898333,700,43,30,20,Urban,0.755,78.94,10.62,0.000,31.17,0.157,126.596313,-74.216313,-77.216313

In [5]:
preprocessor = joblib.load(
    "../ml/saved_models/preprocessor.pkl"
)

In [6]:
X = df.drop(
    columns=["rsrp"]
)

y = df["rsrp"]

In [7]:
X_processed = preprocessor.transform(X)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X_processed,
    y,
    test_size=0.2,
    random_state=42
)

In [9]:
linear_model = LinearRegression()

linear_model.fit(
    X_train,
    y_train
)


linear_prediction = linear_model.predict(
    X_test
)

In [10]:
print("Linear Regression")

print(
    "MAE:",
    mean_absolute_error(
        y_test,
        linear_prediction
    )
)

print(
    "RMSE:",
    mean_squared_error(
        y_test,
        linear_prediction
    )**0.5
)

print(
    "R2:",
    r2_score(
        y_test,
        linear_prediction
    )
)

Linear Regression
MAE: 1.53221435539308e-14
RMSE: 1.992435823448726e-14
R2: 1.0

In [11]:
rf_model = RandomForestRegressor(

    n_estimators=200,

    random_state=42,

    n_jobs=-1
)


rf_model.fit(
    X_train,
    y_train
)


rf_prediction = rf_model.predict(
    X_test
)

In [12]:
print("Random Forest")

print(
    "MAE:",
    mean_absolute_error(
        y_test,
        rf_prediction
    )
)


print(
    "RMSE:",
    mean_squared_error(
        y_test,
        rf_prediction
    )**0.5
)


print(
    "R2:",
    r2_score(
        y_test,
        rf_prediction
    )
)

Random Forest
MAE: 0.0009343837243051248
RMSE: 0.0285724154473324
R2: 0.9999892438299361

In [13]:
gb_model = GradientBoostingRegressor(

    n_estimators=200,

    learning_rate=0.05,

    random_state=42
)


gb_model.fit(
    X_train,
    y_train
)


gb_prediction = gb_model.predict(
    X_test
)

In [14]:
print("Gradient Boosting")

print(
    "MAE:",
    mean_absolute_error(
        y_test,
        gb_prediction
    )
)


print(
    "RMSE:",
    mean_squared_error(
        y_test,
        gb_prediction
    )**0.5
)


print(
    "R2:",
    r2_score(
        y_test,
        gb_prediction
    )
)

Gradient Boosting
MAE: 0.03367577042078085
RMSE: 0.04672569394390177
R2: 0.9999712342787455

In [15]:
results = pd.DataFrame({

    "Model":[
        "Linear Regression",
        "Random Forest",
        "Gradient Boosting"
    ],

    "MAE":[

        mean_absolute_error(y_test, linear_prediction),

        mean_absolute_error(y_test, rf_prediction),

        mean_absolute_error(y_test, gb_prediction)

    ],

    "RMSE":[

        mean_squared_error(y_test, linear_prediction)**0.5,

        mean_squared_error(y_test, rf_prediction)**0.5,

        mean_squared_error(y_test, gb_prediction)**0.5

    ],

    "R2":[

        r2_score(y_test, linear_prediction),

        r2_score(y_test, rf_prediction),

        r2_score(y_test, gb_prediction)

    ]

})


results

               Model           MAE          RMSE        R2
0  Linear Regression  1.532214e-14  1.992436e-14  1.000000
1      Random Forest  9.343837e-04  2.857242e-02  0.999989
2  Gradient Boosting  3.367577e-02  4.672569e-02  0.999971

In [18]:
joblib.dump(
    linear_model,
    "../ml/saved_models/rsrp_linear_model.pkl"
)

['../ml/saved_models/rsrp_linear_model.pkl']